### ISSUE TITLE
「チャプター」の用法

### ISSUE THREAD

**Issue by susurri** [yo-goto/zenn-public-repo#23]
books/js-async-promise-chain-event-loop 以下で、
「チャプター」を「章」の下位の単位として使用されていますが、チャプターは章という意味ですので、「セクション」もしくは「節」とするのが正しいと思います。

**Comment by yo-goto** [comment]
指摘ありがとうございます。たしかに、よく考えたらおかしい感じになってましたね。第一節という感じに修正してみようと思います。

**Comment by yo-goto** [comment]
節(Section)だとより小さいものになってしまうので、以下のコミットで章(Chapter)→部(Part)に修正しました。
https://github.com/yo-goto/zenn-public-repo/commit/f40385508d33c04ea66ef7f87b3604821a139801
