### ISSUE TITLE
books/js-async-promise-chain-event-loop/h-epasync-catch-finally.md の「値をつなぐことはできる」のコード

### ISSUE THREAD

**Issue by susurri** [yo-goto/zenn-public-repo#24]
```
Promise.resolve(42)
  .finally(x => {
    console.log(x); // => undefined
    return 33;
  })
  .then(console.log); // => 33
```
を deno run で実行すると
```
undefined
42
```
となり、33 は出力されません。

**Comment by yo-goto** [comment]
指摘ありがとうございます。この箇所は私の間違いだと思います。
値をつなぐことはできませんでした。後ほど修正しておきます!!

**Comment by yo-goto** [comment]
@susurri 
指摘していただいた箇所を修正しました。
以下のコミットから該当の箇所の修正を確認できます。

https://github.com/yo-goto/zenn-public-repo/commit/db84f5e21d3892c2e1013ab811ea75921c776196

誤った情報を記載してしまいごめんなさい🙇‍♂️
また何か間違いを見つけたら教えていただけると助かります!
