### ISSUE TITLE
The module's source code could not be parsed: Expected '{', got '=>' at file...

### ISSUE THREAD

**Issue by mendelssohnbach** [yo-goto/zenn-public-repo#3]
https://github.com/yo-goto/zenn-public-repo/blob/d82b355438fcf63404bfdf63fc63680c1d4fb068/books/js-async-promise-chain-event-loop/b-epasync-callstack-execution-context.md?plain=1#L190

有用な資料公開ありがとうございます。

```javascript
  .then(function microTaskFunc(){
```

余分な `=>` が記述されているようです。

**Comment by yo-goto** [comment]
指摘ありがとうございます!
修正いたしました👍
