### ISSUE TITLE
Typo 修正

### ISSUE THREAD

**Issue by mendelssohnbach** [yo-goto/zenn-public-repo#4]
https://github.com/yo-goto/zenn-public-repo/blob/b1ffab6c360aeb26c92ddd577e7b307f827d5fdb/books/js-async-promise-chain-event-loop/j-epasync-ts-promise-type-annotation.md?plain=1#L1319

有用な資料公開ありがとうございます。

```
function pTimer (
  time: number
): Promise<number> {
  return new Promise((resolve) => setTimeout(() => {
    console.log(`${time}[ms]でタイムアウトしました`)
    // reoslve(time);
    // }), time);
    resolve(time);
  }, time));
}
```

`reoslve` --> `resolve`

`}), time)` --> `}, time))`

自信を持って非同期処理を記述できるようになりました。
深く感謝します。

**Comment by yo-goto** [comment]
ありがとうございます!
そう言っていただけると非常に嬉しいです。

また、指摘ありがとうございした。タイポ等修正しました👍
